version: '3.8'

services:
  adobe-contest:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      # Contest required environment variables
      - ADOBE_EMBED_API_KEY=${ADOBE_EMBED_API_KEY:-}
      - LLM_PROVIDER=${LLM_PROVIDER:-gemini}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/credentials/adbe-gcp.json}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - TTS_PROVIDER=${TTS_PROVIDER:-azure}
      - AZURE_TTS_KEY=${AZURE_TTS_KEY:-}
      - AZURE_TTS_ENDPOINT=${AZURE_TTS_ENDPOINT:-}
      
      # Ollama configuration for local development
      - OLLAMA_BASE_URL=http://localhost:11434
      - OLLAMA_MODEL=llama3
      - USE_API_EMBEDDINGS=true
      - EMBEDDING_API_TYPE=ollama
      
      # Development overrides
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/backend
    volumes:
      # Mount credentials directory
      - ${CREDENTIALS_PATH:-./credentials}:/credentials:ro
      # Mount for development (optional)
      # - ./combined-backend:/app/backend
      # - ./adobe_frontend/build:/app/frontend
    networks:
      - adobe-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  adobe-network:
    driver: bridge

# Example usage commands:
# 
# Build and run with Gemini (contest default):
# docker-compose up --build
#
# Run with local Ollama:
# LLM_PROVIDER=ollama docker-compose up
#
# Run with custom credentials path:
# CREDENTIALS_PATH=/path/to/your/credentials docker-compose up
#
# Contest evaluation command equivalent:
# docker build --platform linux/amd64 -t adobe-contest .
# docker run -v /path/to/credentials:/credentials \
#   -e ADOBE_EMBED_API_KEY=your_key \
#   -e LLM_PROVIDER=gemini \
#   -e GOOGLE_APPLICATION_CREDENTIALS=/credentials/adbe-gcp.json \
#   -e GEMINI_MODEL=gemini-2.5-flash \
#   -e TTS_PROVIDER=azure \
#   -e AZURE_TTS_KEY=your_tts_key \
#   -e AZURE_TTS_ENDPOINT=your_tts_endpoint \
#   -p 8080:8080 adobe-contest
